defaults:
  - dataset: custom_video
  - eval: null
  - engine: offline
  - visualization: gamestate
  - modules/bbox_detector: yolo_ultralytics
  - modules/reid: prtreid
  - modules/track: bpbreid_strong_sort
  - modules/jersey_number_detect: mmocr
  - modules/team: kmeans_embeddings
  - modules/team_side: mean_position
  - modules/tracklet_agg: voting_role_jn
  - modules/pitch: nbjw_calib
  - modules/calibration: nbjw_calib
  - _self_

pipeline:
  - bbox_detector
  - reid
  - track
  - pitch
  - calibration
  - jersey_number_detect
  - tracklet_agg
  - team
  - team_side

experiment_name: "custom-video-test"

data_dir: "${project_dir}/data"
model_dir: "${project_dir}/pretrained_models"

modules:
  bbox_detector: {batch_size: 4}
  reid: {batch_size: 32}
  track: {batch_size: 32}
  pitch: {batch_size: 1}
  calibration: {batch_size: 1}
  jersey_number_detect: {batch_size: 4}

test_tracking: True
eval_tracking: False

dataset:
  nvid: 1
  dataset_path: ${data_dir}/custom_video

visualization:
  cfg:
    save_videos: True
